import { depker, nextjs } from "https://raw.githubusercontent.com/syfxlin/depker/master/mod.ts";

const app = depker();

app.service(
  nextjs({
    name: "blog",
    domain: "blog.ixk.me",
    tls: true,
    secrets: {
      NEXT_PUBLIC_COLINE_LANGUAGE: "@COLINE_LANGUAGE",
      NEXT_PUBLIC_COLINE_GOOGLE_ANALYTICS: "@COLINE_GOOGLE_ANALYTICS",
      NEXT_PUBLIC_COLINE_ARTALK_SITE_NAME: "@COLINE_ARTALK_SITE_NAME",
      NEXT_PUBLIC_COLINE_ARTALK_SERVER_URL: "@COLINE_ARTALK_SERVER_URL",
      NEXT_PUBLIC_COLINE_GITHUB_REPO: "@COLINE_GITHUB_REPO",
      COLINE_GITHUB_TOKEN: "@COLINE_GITHUB_TOKEN",
      KEYSTATIC_SECRET: "@KEYSTATIC_SECRET",
      KEYSTATIC_GITHUB_CLIENT_ID: "@KEYSTATIC_GITHUB_CLIENT_ID",
      KEYSTATIC_GITHUB_CLIENT_SECRET: "@KEYSTATIC_GITHUB_CLIENT_SECRET",
      NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: "@KEYSTATIC_GITHUB_APP_SLUG",
    },
  }),
);

export default app;
