main:
  - title: 归档
    link: /archives
    icon: ri:archive-line
    view: elastic
  - title: GitHub
    link: https://github.com/syfxlin/next-theme-coline
    icon: uil:github-alt
    view: elastic-icon
