link: https://blog.ixk.me
logo: /image/config/seo/logo.400x400.jpg
title: 青空之蓝
subtitle: 站在时光一端，回忆过往记忆。
description: >-
  青空之蓝（博客）- Otstar Lin (@syfxlin，繁星) 在互联网上的一片小天地，随便写点东西的地方。技术博客，以 Java
  后端开发，前端开发相关内容为主。
birthday: 2017-07-01T00:00
keywords:
  - Otstar Lin
  - syfxlin
  - Blog
  - 博客
  - Java
  - JavaScript
  - TypeScript
  - Full Stack
