link: https://coline.ixk.me
logo: /image/config/seo/logo.400x400.jpg
title: Coline
subtitle: 轻快、简洁、优雅的 Next.js 模板
description: >-
  Coline（connect, line）是一个基于 Next.js App Router
  开发的博客模板，建立在轻快与简洁的设计理念上，摒弃花里胡哨的界面，专注于内容创作。
birthday: 2024-01-01T00:00
keywords:
  - Otstar Lin
  - syfxlin
  - Blog
  - 博客
  - Next.js
  - Next.js App Router
