links:
  - name: Pasi's Studio
    author: Pasi
    link: https://pasi.cat/
    avatar: images/pasi.cat.jpg
    bio: 404 Not Found
  - name: 诸葛小百科
    author: 苏苏
    link: https://www.xiaobaike.net/
    avatar: images/www.xiaobaike.net.png
    bio: 技术.生活.记录.音乐
  - name: 天空·边界
    author: 天空之间
    link: https://liyin.date
    avatar: images/liyin.date.png
    bio: 用心探知天空的边界
  - name: 晴耕物语博客
    link: https://www.sayxw.top
    avatar: images/www.sayxw.top.png
    bio: 晴天丶故事丶雨声丶平静的心。
  - name: stackboom
    author: stackboom
    link: http://stackboom.xin
    avatar: images/stackboom.xin.jpg
    bio: 事情多了，得记记
  - name: Zavier's Blog
    author: Zavier
    link: https://zavierlab.com
    avatar: images/zavierlab.com.png
    bio: 平淡就好
  - name: 蠢黑通行
    author: 蠢黑通行
    link: https://blackyau.cc
    avatar: images/blackyau.cc.png
  - name: 下午茶的轻音部
    author: Haibara
    link: https://www.myeriri.com/
    avatar: images/www.myeriri.com.png
  - name: 恶魔菌の记事簿
    author: 恶魔菌
    link: https://meow3.family.blog/
    avatar: images/meow3.family.blog.png
    bio: 半文艺、半动漫的二次元美少女的涂鸦簿！
  - name: Zohar's Blog
    author: Zohar
    link: https://www.iwch.me
    avatar: images/www.iwch.me.png
    bio: The Most Important Thing in My Life is Freedom
  - name: 萨摩公园
    author: Meto
    link: https://i-meto.com
    avatar: images/i-meto.com.png
    bio: 我就是我，不食人间烟火
  - name: 奶冰の冷藏室
    author: Milkice
    link: https://milkice.me
    avatar: images/milkice.me.png
    bio: Maybe a way to explore the world?
  - name: KeJun's Blog
    author: KeJun
    link: https://kejun.me
    avatar: images/kejun.me.png
    bio: 二次元智障
  - name: 梦之翼
    author: Fly3949
    link: https://fly.moe
    avatar: images/fly.moe.png
    bio: Flyの宅基地
  - name: Elepover's Blog
    author: Elepover
    link: https://daily.elepover.com/
    avatar: images/see.wtf.png
    bio: 没有人能阻挡，我们与生俱来对自由的渴望
  - name: 无垠
    author: Axton
    link: https://flyhigher.top
    avatar: images/flyhigher.top.png
    bio: 飞翔的天空无限大
  - name: 苏卡卡的有底洞
    author: Sukka
    link: https://skk.moe
    avatar: images/skk.moe.png
    bio: "「童话只美在真实却从不续写」"
  - name: "⑨BIE"
    author: "⑨BIE"
    link: https://9bie.org/
    avatar: images/9bie.org.jpg
    bio: 伪技术宅的谜之地
  - name: Re:Vigorous Pro
    author: Edison Jwa
    link: https://www.wevg.org
    avatar: images/www.wevg.org.jpg
    bio: Hi, nice to meet you.这是一个从零开始的世界
  - name: Indexyz's Blog
    author: Indexyz
    link: https://blog.indexyz.me/
    avatar: images/blog.indexyz.me.jpg
    bio: Sharing light, even in death.
  - name: 黄蜂说
    author: a.k.a. 小黄蜂
    link: https://www.sjy.im/
    avatar: images/www.sjy.im.png
    bio: 一名互联网从业者的自留地，分享自己的所见所得，自认为过程比结果重要。
  - name: NEVER迷の小窝
    author: NeverBehave
    link: https://blog.never.pet
    avatar: images/blog.never.pet.png
    bio: 喵喵喵～
  - name: idealclover
    author: idealclover
    link: https://idealclover.top
    avatar: images/idealclover.top.jpg
    bio: 翠翠酱的个人网站
  - name: 罗炜杰个人博客
    author: 不必谁懂我
    link: https://www.lwjppz.cn/
    avatar: images/www.lwjppz.cn.jpg
    bio: 记录写代码的苦逼日子
  - name: 小竹's blog
    author: 小竹
    link: https://blog.justforlxz.com/
    avatar: images/blog.justforlxz.com.png
    bio: 永远不要停止思考
  - name: N0ts Blog
    author: N0tssss
    link: https://blog.n0ts.cn
    avatar: images/blog.n0ts.cn.jpg
    bio: 一个爱好钻研技术的学生党博客
  - name: 辣椒の酱
    author: 辣椒の酱
    link: https://removeif.github.io/
    avatar: images/removeif.github.io.jpg
    bio: 后端开发，技术分享
  - name: 蝉時雨
    author: 蝉時雨
    link: https://chanshiyu.com/
    avatar: images/chanshiyu.com.jpg
    bio: 蝉鸣如雨 花宵道中
  - name: Jing blog
    author: Chris
    link: https://jingine.com/
    avatar: images/jingine.com.png
  - name: TonyHe
    author: TonyHe
    link: https://www.ouorz.com/
    avatar: images/ouorz.com.jpg
    bio: Just A Poor Lifesinger
  - name: Cyberspace of Swung
    author: Swung0x48
    link: https://www.swung0x48.com
    avatar: images/swung0x48.com.jpg
    bio: Lost in cyberpunk.
  - name: WenJie' Blog
    author: chenwenjie
    link: https://wenjie.store/
    avatar: images/wenjie.store.jpg
    bio: 记录一些学习笔记、杂谈
  - name: 蚊Blog
    author: 贫困の蚊子
    link: https://qwq.moe/
    avatar: images/qwq.moe.png
  - name: Cyris
    author: Cyris
    link: https://cyris.moe/
    avatar: images/cyris.moe.png
    bio: 花如解笑还多事，石不能言最可人
  - name: Cotpear
    author: 齊一和其團隊
    link: https://www.cotpear.com?utm_src=blog.ixk.me
    avatar: images/www.cotpear.com.jpg
  - name: QWQAQ
    author: qwqaq
    link: https://qwqaq.com/
    avatar: images/qwqaq.com.png
    bio: 生命不止，折腾不息 ( ゜- ゜)
  - name: OS0day
    link: https://blog.os0day.cn/
    author: OS0day
    bio: 一位医疗行业的软件工程师
    avatar: images/blog.os0day.cn.png
  - link: https://0m0.co/
    name: 冰糕Luminous の 小窝
    author: 冰糕Luminous
    avatar: images/0m0.co.png
lost_links:
  - name: 周海棠啦
    link: https://begonia98.github.io
  - name: Viosey's Blog
    link: https://blog.viosey.com
  - name: neoFelhz's Blog
    link: https://nfz.moe
