links:
  - name: Pasi's Studio
    link: https://pasi.cat/
    avatar: /image/links/0/avatar.640x640.jpg
    author: Pasi
    description: 404 Not Found
lost_links:
  - name: 周海棠啦
    link: https://begonia98.github.io
