main:
  - title: 项目
    link: https://github.com/syfxlin?tab=repositories&type=source
    icon: ri:box-3-line
    view: elastic
  - title: 归档
    link: /archives
    icon: ri:archive-line
    view: elastic
  - title: 友邻
    link: /links
    icon: ri:heart-line
    view: elastic
  - title: 自述
    link: /about
    icon: ri:user-line
    view: elastic
  - title: 留言
    link: /message-board
    icon: ri:message-3-line
    view: elastic
  - title: GitHub
    link: https://github.com/syfxlin
    icon: uil:github-alt
    view: elastic-icon
  - title: Twitter
    link: https://twitter.com/syfxlin
    icon: uil:twitter-alt
    view: elastic-icon
  - title: Telegram
    link: https://t.me/otstar
    icon: uil:telegram-alt
    view: elastic-icon
