categories:
  - name: Focus
    items:
      - name: Reve
        icon: lucide:ice-cream
        link: https://github.com/syfxlin/reve
        description: >-
          Reve is a library of enhancements to vanilla-extract to improve the
          experience of using vanilla-extract and reduce unnecessary time
          consumption due to specific programming paradigms.
