body:
  discriminant: none
categories:
  - name: Focus
    projects:
      - name: Reve
        link: https://github.com/syfxlin/reve
        description: >-
          Reve is a library of enhancements to vanilla-extract to improve the
          experience of using vanilla-extract and reduce unnecessary time
          consumption due to specific programming paradigms.
        components:
          - simple-icons:typescript
          - simple-icons:css3
          - simple-icons:styledcomponents
