name: Next Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Depker
        run: |
          deno install -A https://raw.githubusercontent.com/syfxlin/depker/master/depker.ts --root /usr/local --name depker
      - name: Deploy to docker
        run: |
          echo "$SECRETS_ENV" > .env
          depker service deploy
        env:
          TZ: Asia/Shanghai
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_CA: ${{ secrets.REMOTE_CA }}
          REMOTE_CERT: ${{ secrets.REMOTE_CERT }}
          REMOTE_KEY: ${{ secrets.REMOTE_KEY }}
          SECRETS_ENV: ${{ secrets.SECRETS_ENV }}
